name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  testes:
    name: Rodar Testes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn -B test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

  empacotar:
    name: Empacotar Projeto
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build package
        run: mvn -B -DskipTests package

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/*.jar

  notificacao:
    name: Enviar Notificação por E-mail
    runs-on: ubuntu-latest
    needs: [testes, empacotar]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp ca-certificates

      - name: Garantir permissão de execução
        run: chmod +x .github/scripts/send_email.sh

      - name: Executar script de envio de email
        run: |
          SUBJECT="📢 Pipeline finalizado para ${{ github.repository }} (branch ${{ github.ref_name }})"
          BODY="Resultados:\n- Testes: ${{ needs.testes.result }}\n- Empacotar: ${{ needs.empacotar.result }}\n\nVeja os artifacts do run em: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          bash .github/scripts/send_email.sh "$SUBJECT" "$BODY"
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
